backend:
  name: github
  repo: oricha-25/dexter-infinite-portfolio
  branch: main
  base_url: https://decap-oauth-worker.orichahmed.workers.dev
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "projects"
    label: "Featured Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Database Engine", name: "database", widget: "string", default: "PostgreSQL" }
      - { label: "Live App URL", name: "live_url", widget: "string" }
      - { label: "GitHub Repo URL", name: "github_url", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
